Repository cloudposse/terraform-aws-cloudfront-cdn, pull requests merged in 2024-03, with the labels that each got.

#115 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#118 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, migration

#117 Update default minimum viewer protocol to TLSv1.2_2021
  README.md
  docs/terraform.md
  variables.tf
Labels: patch
